[package]
name = "starcoin-transactional-test-harness"
version = "0.1.0"
edition = "2018"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "~1"
once_cell = "~1"
anyhow = "~1"
structopt = "~0.3"
bcs = "~0.1"
itertools = "~0.10"

move-transactional-test-runner = { git = "https://github.com/starcoinorg/diem", rev="6ff224f42a408f584acbcd37eebac14de619b16f" }
move-lang = { git = "https://github.com/starcoinorg/diem", rev="6ff224f42a408f584acbcd37eebac14de619b16f" }
move-binary-format = { git = "https://github.com/starcoinorg/diem", rev="6ff224f42a408f584acbcd37eebac14de619b16f" }
move-core-types = { git = "https://github.com/starcoinorg/diem", rev="6ff224f42a408f584acbcd37eebac14de619b16f" }
move-command-line-common = { git = "https://github.com/starcoinorg/diem", rev="6ff224f42a408f584acbcd37eebac14de619b16f" }


starcoin-crypto = {path = "../../commons/crypto"}
stdlib = {path = "../stdlib"}
starcoin-genesis = {path = "../../genesis"}
starcoin-config = { path = "../../config"}
starcoin-statedb = { path = "../../state/statedb"}
starcoin-state-api = {path = "../../state/api"}
starcoin-vm-types = {path = "../../vm/types"}
starcoin-types = {path = "../../types"}
starcoin-rpc-api = {path = "../../rpc/api"}
starcoin-vm-runtime = {path = "../../vm/vm-runtime"}
starcoin-dev = {path = "../dev"}
starcoin-resource-viewer = {path = "../resource-viewer"}
resource-viewer = {git = "https://github.com/starcoinorg/diem", rev="6ff224f42a408f584acbcd37eebac14de619b16f"}
[dev-dependencies]
datatest-stable = "0.1"

[[test]]
name = "tests"
harness = false
